import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import { ClerkProvider } from "@clerk/nextjs";
import { neobrutalism } from "@clerk/themes";
import UserSyncWrapper from "@/components/UserSyncWrapper"; // Adjust path as needed

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "ReWear",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider appearance={{ baseTheme: neobrutalism }}>
      <html lang="en" suppressHydrationWarning>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          {/* User sync component */}
          <UserSyncWrapper />
          
          {/* Header */}
          <Header />
          <main className="min-h-screen">{children}</main>

          {/* footer
          <footer className="bg-[#f9f7f6] py-12">
            <div className="container mx-auto px-4 text-center text-gray-600">
              <p> ReWear </p>
            </div>
          </footer> */}
        </body>
      </html>
    </ClerkProvider>
  );
}